# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e998b629d4fe09b2a50cbe73ef5d511b"
application_url = "https://necessarily-teen-columnists-containers.trycloudflare.com"
embedded = true
name = "store-data-app"
handle = "store-data-app-2"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products,read_customers,write_customers,read_inventory,write_inventory,read_draft_orders,write_draft_orders,read_marketing_events,write_marketing_events,read_themes,write_themes,read_checkouts,write_checkouts"

[auth]
redirect_urls = [
  "https://necessarily-teen-columnists-containers.trycloudflare.com/auth/callback",
  "https://necessarily-teen-columnists-containers.trycloudflare.com/auth/shopify/callback",
  "https://necessarily-teen-columnists-containers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "jeel-dev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
